export const CATEGORY_PAGE_COPY = {
  title: "Kategori",
  description: "Kelola kelompok barang agar pencarian dan filter stok lebih mudah.",
  tableTitle: "Daftar Kategori",
  searchPlaceholder: "Cari nama kategori...",
  emptyDescription: "Belum ada kategori yang sesuai.",
  loadingDescription: "Memuat kategori...",
  errorTitle: "Kategori gagal dimuat",
  addCategory: "Tambah Kategori",
  editCategory: "Edit Kategori",
  createModalTitle: "Tambah kategori",
  editModalTitle: "Edit kategori",
  deleteTitle: "Hapus kategori?",
  deleteDescription: "Kategori akan dihapus dari daftar. Barang yang memakai kategori ini tidak ikut terhapus.",
  deleteOkText: "Hapus",
  cancelText: "Batal",
  saveText: "Simpan",
  createSuccess: "Kategori berhasil ditambahkan.",
  updateSuccess: "Kategori berhasil diperbarui.",
  deleteSuccess: "Kategori berhasil dihapus.",
  nameLabel: "Nama kategori",
  namePlaceholder: "Contoh: Ayam",
  descriptionLabel: "Deskripsi",
  descriptionPlaceholder: "Catatan singkat untuk kategori ini",
  nameHelp: "Gunakan nama singkat yang mudah dipakai untuk filter barang.",
  descriptionHelp: "Opsional. Isi jika kategori perlu keterangan tambahan untuk staf.",
  searchLabel: "Pencarian kategori",
  showingItems: "Menampilkan",
  itemSuffix: "kategori",
} as const;

export const CATEGORY_TABLE_COPY = {
  name: "Nama kategori",
  description: "Deskripsi",
  updatedAt: "Terakhir diperbarui",
  actions: "Aksi",
  edit: "Edit",
  delete: "Hapus",
  noDescription: "-",
} as const;
