export const ITEM_PAGE_COPY = {
  createModalTitle: "Tambah barang",
  editModalTitle: "Edit barang",
  detailTitle: "Detail barang",
  detailDescription: "Informasi stok, harga, dan kategori barang.",
  deleteTitle: "Hapus barang?",
  deleteDescription: "Barang akan dihapus dari daftar stok.",
  deleteOkText: "Hapus",
  cancelText: "Batal",
  saveText: "Simpan",
  createSuccess: "Barang berhasil ditambahkan.",
  updateSuccess: "Barang berhasil diperbarui.",
  deleteSuccess: "Barang berhasil dihapus.",
  errorTitle: "Barang gagal dimuat",
  emptyDescription: "Belum ada barang yang sesuai.",
  backToDashboard: "Kembali",
  addItem: "Tambah Barang",
  searchLabel: "Pencarian barang",
  categoryFilterLabel: "Filter kategori barang",
  allCategories: "Semua kategori",
  noCategory: "Tanpa kategori",
  noValue: "-",
  outOfStock: "Stok habis",
  lowStock: "Menipis",
  available: "Tersedia",
} as const;

export const LOW_STOCK_THRESHOLD = 20;

export const ITEM_FORM_COPY = {
  nameLabel: "Nama barang",
  namePlaceholder: "Contoh: Ayam nugget crispy",
  categoryLabel: "Kategori",
  categoryPlaceholder: "Pilih kategori",
  stockLabel: "Stok",
  minimumStockLabel: "Batas stok minimum",
  unitLabel: "Satuan",
  unitPlaceholder: "Contoh: pcs, pack, box",
  packageSizeLabel: "Berat / ukuran",
  packageSizePlaceholder: "Contoh: 500 gram",
  purchasePriceLabel: "Harga beli",
  sellingPriceLabel: "Harga jual",
  storageLocationLabel: "Lokasi penyimpanan",
  storageLocationPlaceholder: "Contoh: Freezer A-01",
  photoUrlLabel: "URL foto",
  photoUrlPlaceholder: "Akan terisi dari upload foto pada milestone berikutnya",
  descriptionLabel: "Deskripsi",
  descriptionPlaceholder: "Catatan tambahan barang",
  nameRequired: "Nama barang wajib diisi.",
  stockRequired: "Stok wajib diisi.",
  unitRequired: "Satuan wajib diisi.",
  minimumStockRequired: "Batas stok minimum wajib diisi.",
  sellingPriceRequired: "Harga jual wajib diisi.",
} as const;

export const ITEM_TABLE_COPY = {
  itemName: "Nama barang",
  category: "Kategori",
  stock: "Stok",
  unit: "Satuan",
  packageSize: "Ukuran",
  sellingPrice: "Harga jual",
  actions: "Aksi",
  detail: "Detail",
  edit: "Edit",
  delete: "Hapus",
} as const;

export const ITEM_DETAIL_COPY = {
  name: "Nama barang",
  category: "Kategori",
  stock: "Stok",
  minimumStock: "Batas stok minimum",
  unit: "Satuan",
  packageSize: "Berat / ukuran",
  purchasePrice: "Harga beli",
  sellingPrice: "Harga jual",
  storageLocation: "Lokasi penyimpanan",
  photoUrl: "URL foto",
  description: "Deskripsi",
  createdAt: "Dibuat",
  updatedAt: "Diperbarui",
} as const;

export const ITEM_UNIT_OPTIONS = [
  { label: "pcs", value: "pcs" },
  { label: "pack", value: "pack" },
  { label: "box", value: "box" },
  { label: "kg", value: "kg" },
  { label: "gram", value: "gram" },
] as const;
