export const ITEM_PAGE_COPY = {
  createModalTitle: "Tambah barang",
  editModalTitle: "Edit barang",
  detailTitle: "Detail barang",
  detailDescription: "Informasi stok, harga, dan kategori barang.",
  deleteTitle: "Hapus barang?",
  deleteDescription: "Barang akan dihapus dari daftar stok.",
  deleteOkText: "Hapus",
  cancelText: "Batal",
  saveText: "Simpan",
  createSuccess: "Barang berhasil ditambahkan.",
  updateSuccess: "Barang berhasil diperbarui.",
  deleteSuccess: "Barang berhasil dihapus.",
  errorTitle: "Barang gagal dimuat",
  emptyDescription: "Belum ada barang yang sesuai.",
  backToDashboard: "Kembali",
  addItem: "Tambah Barang",
  searchLabel: "Pencarian barang",
  categoryFilterLabel: "Filter kategori barang",
  allCategories: "Semua kategori",
  noCategory: "Tanpa kategori",
  noValue: "-",
  outOfStock: "Stok habis",
  lowStock: "Menipis",
  available: "Tersedia",
} as const;

export const LOW_STOCK_THRESHOLD = 20;

export const ITEM_FORM_COPY = {
  nameLabel: "Nama barang",
  namePlaceholder: "Contoh: Ayam nugget crispy",
  categoryLabel: "Kategori",
  categoryPlaceholder: "Pilih kategori",
  stockLabel: "Jumlah stok",
  minimumStockLabel: "Stok minimum",
  unitLabel: "Satuan",
  unitPlaceholder: "Pilih satuan",
  packageSizeLabel: "Berat / ukuran",
  packageSizePlaceholder: "Contoh: 500 gram",
  purchasePriceLabel: "Harga beli (Rp)",
  sellingPriceLabel: "Harga jual (Rp)",
  storageLocationLabel: "Lokasi simpan",
  storageLocationPlaceholder: "Contoh: Freezer A-01",
  photoUrlLabel: "Foto barang",
  photoUrlHelp: "Opsional. Foto membantu staf mengenali barang saat pengecekan stok.",
  photoUploadHint: "Format: JPG, PNG atau WEBP - Maks. 2 MB",
  photoUploadText: "Klik untuk memilih foto, atau seret file ke sini",
  photoUploadButton: "Pilih Foto",
  photoUploadSuccess: "Foto berhasil diunggah.",
  photoUploadRemove: "Foto akan dihapus dari data barang saat disimpan.",
  photoUploadTypeError: "Foto harus berformat JPG, PNG, atau WebP.",
  photoUploadSizeError: "Ukuran foto maksimal 2 MB.",
  descriptionLabel: "Deskripsi",
  descriptionPlaceholder: "Catatan tambahan barang",
  nameHelp: "Gunakan nama barang yang jelas dan mudah dicari.",
  categoryHelp: "Kategori diambil dari data pada halaman Kategori.",
  stockHelp: "Isi jumlah stok fisik barang saat ini.",
  minimumStockHelp: "Batas stok untuk membantu menandai barang yang perlu segera diisi ulang.",
  unitHelp: "Pilih satuan utama stok, misalnya pcs, pack, box, kg, atau gram.",
  packageSizeHelp: "Isi ukuran kemasan seperti 500 gram, 1 kg, atau 20 pcs.",
  purchasePriceHelp: "Harga beli per satuan dalam rupiah.",
  sellingPriceHelp: "Harga jual per satuan dalam rupiah.",
  storageLocationHelp: "Lokasi penyimpanan barang, misalnya freezer atau rak.",
  descriptionHelp: "Opsional. Isi informasi tambahan yang membantu staf.",
  nameRequired: "Nama barang wajib diisi.",
  categoryRequired: "Kategori wajib dipilih.",
  stockRequired: "Stok wajib diisi.",
  unitRequired: "Satuan wajib diisi.",
} as const;

export const ITEM_TABLE_COPY = {
  itemName: "Nama barang",
  category: "Kategori",
  stock: "Stok",
  unit: "Satuan",
  packageSize: "Ukuran",
  sellingPrice: "Harga jual",
  actions: "Aksi",
  detail: "Detail",
  edit: "Edit",
  delete: "Hapus",
} as const;

export const ITEM_DETAIL_COPY = {
  name: "Nama barang",
  category: "Kategori",
  stock: "Stok",
  minimumStock: "Batas stok minimum",
  unit: "Satuan",
  packageSize: "Berat / ukuran",
  purchasePrice: "Harga beli",
  sellingPrice: "Harga jual",
  storageLocation: "Lokasi penyimpanan",
  photoUrl: "URL foto",
  description: "Deskripsi",
  createdAt: "Dibuat",
  updatedAt: "Diperbarui",
} as const;

export const ITEM_UNIT_OPTIONS = [
  { label: "pcs", value: "pcs" },
  { label: "pack", value: "pack" },
  { label: "box", value: "box" },
  { label: "kg", value: "kg" },
  { label: "gram", value: "gram" },
] as const;
